eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8767
spring:
  application:
    name: service-feign

#¼ÓÈÛ¶ÏÆ÷
feign:
  hystrix:
    enabled: true
#hystrix:
#  command:
#    default:
#      execution:
#        isolation:
#          thread:
#            timeoutInMilliseconds: 100000
#        timeout:
#          enabled: false
#ribbon:
#  ReadTimeout: 5000
#  ConnectTimeout: 3000
#  maxAutoRetries: 1
#  MaxAutoRetriesNextServer: 2
#  OkToRetryOnAllOperations: true